const EPLplayers = [
    'Alexandre Lacazette',
    'Andrew Robertson',
    'Bernardo Silva',
    'Bruno Fernandes',
    'Bukayo Saka',
    'Conor Gallagher',
    'Cristiano Ronaldo',
    'Danny Ings',
    'Dejan Kulusevski',
    'Diogo Jota',
    'Emile Smith Rowe',
    'Emmanuel Dennis',
    'Gabriel Jesus',
    'Harry Kane',
    'Harvey Barnes',
    'İlkay Gündoğan',
    'Ivan Toney',
    'James Maddison',
    'James Ward-Prowse',
    'Jamie Vardy',
    'Jarrod Bowen',
    'Kai Havertz',
    'Kevin De Bruyne',
    'Martinelli',
    'Mason Mount',
    'Michail Antonio',
    'Mohamed Salah',
    'Ollie Watkins',
    'Phil Foden',
    'Raheem Sterling',
    'Raphinha',
    'Reece James',
    'Richarlison',
    'Riyad Mahrez',
    'Sadio Mané',
    'Saïd Benrahma',
    'Son Heung-min',
    'Teemu Pukki',
    'Trent Alexander-Arnold',
    'Wilfried Zaha'
  ];
  
  export default EPLplayers;