const NBAPlayers = [
    'Anthony Davis',
    'Anthony Edwards',
    'Bam Adebayo',
    'Bojan Bogdanovic',
    'Bradley Beal',
    'Brandon Ingram',
    'Damian Lillard',
    'Darius Garland',
    'D\'Angelo Russell',
    'De\'Aaron Fox',
    'DeMar DeRozan',
    'Dejounte Murray',
    'Devin Booker',
    'Dillon Brooks',
    'Donovan Mitchell',
    'Fred VanVleet',
    'Gary Trent Jr.',
    'Giannis Antetokounmpo',
    'Ja Morant',
    'Jaylen Brown',
    'Jayson Tatum',
    'Jeremi Grant',
    'Jimmy Butler',
    'Joel Embiid',
    'Jordan Poole',
    'Jrue Holiday',
    'Julius Randle',
    'Karl-Anthony Towns',
    'Kevin Durant',
    'Khris Middleton',
    'Klay Thompson',
    'Kyrie Irving',
    'LaMelo Ball',
    'LeBron James',
    'Luka Doncic',
    'Malcolm Brogdon',
    'Miles Bridges',
    'Nikola Jokic',
    'Norman Powell',
    'Pascal Siakam',
    'Paul George',
    'RJ Barrett',
    'Russell Westbrook',
    'Shai Gilgeous-Alexander',
    'Stephen Curry',
    'Terry Rozier',
    'Trae Young',
    'Tyler Herro',
    'Zach LaVine'
  ];

  export default NBAPlayers;
  