const Players = [
  "Anthony Davis",
  "Anthony Edwards",
  "Bam Adebayo",
  "Bojan Bogdanovic",
  "Bradley Beal",
  "Brandon Ingram",
  "Damian Lillard",
  "Darius Garland",
  "D'Angelo Russell",
  "De'Aaron Fox",
  "DeMar DeRozan",
  "Dejounte Murray",
  "Devin Booker",
  "Dillon Brooks",
  "Donovan Mitchell",
  "Fred VanVleet",
  "Gary Trent Jr.",
  "Giannis Antetokounmpo",
  "Ja Morant",
  "Jaylen Brown",
  "Jayson Tatum",
  "Jeremi Grant",
  "Jimmy Butler",
  "Joel Embiid",
  "Jordan Poole",
  "Jrue Holiday",
  "Julius Randle",
  "Karl-Anthony Towns",
  "Kevin Durant",
  "Khris Middleton",
  "Klay Thompson",
  "Kyrie Irving",
  "LaMelo Ball",
  "LeBron James",
  "Luka Doncic",
  "Malcolm Brogdon",
  "Miles Bridges",
  "Nikola Jokic",
  "Norman Powell",
  "Pascal Siakam",
  "Paul George",
  "RJ Barrett",
  "Russell Westbrook",
  "Shai Gilgeous-Alexander",
  "Stephen Curry",
  "Terry Rozier",
  "Trae Young",
  "Tyler Herro",
  "Zach LaVine",
  "Cade Cunningham",
  "Jalen Green",
  "Anfernee Simons",
  "Deandre Ayton",
  "Luguentz Dort",
  "Tobias Harris",
  "Andrew Wiggins",
  "OG Anunoby",
  "Kyle Kuzma",
  "Keldon Johnson",
  "Reggie Jackson",
  "Harrison Barnes",
  "Cole Anthony",
  "Jalen Brunson",
  "Jaren Jackson Jr.",
  "John Collins",
  "Jarrett Allen",
  "Saddiq Bey",
  "Jordan Clarkson",
  "Collin Sexton",
  "Gordon Hayward",
  "Rudy Gobert",
  "Kevin Porter Jr.",
  "Marcus Morris",
  "Scottie Barnes",
  "Jordan Poole",
  "Russell Westbrook",
  "Dillon Brooks",
  "Jrue Holiday",
  "Gary Trent Jr.",
  "Desmond Bane",
  "Tyrese Maxey",
  "Wendell Carter Jr.",
  "Aaron Gordon",
  "Evan Mobley",
  "Jusuf Nurkić",
  "Kelly Oubre Jr.",
  "Jonas Valančiūnas",
  "Nikola Vučević",
];

const NBAPlayers = Array.from(new Set(Players));

NBAPlayers.sort();

export default NBAPlayers;
