const NBAPlayers = [
    'Anthony Davis',
    'Anthony Edwards',
    'Bam Adebayo',
    'Bradley Beal',
    'Bojan Bogdanovic',
    'Damian Lillard',
    'De\'Aaron Fox',
    'DeMar DeRozan',
    'Dejounte Murray',
    'Dillon Brooks',
    'D\'Angelo Russell',
    'Darius Garland',
    'Devin Booker',
    'Donovan Mitchell',
    'Fred VanVleet',
    'Gary Trent Jr.',
    'Giannis Antetokounmpo',
    'Jrue Holiday',
    'Jaylen Brown',
    'Jayson Tatum',
    'Joel Embiid',
    'Jordan Poole',
    'Julius Randle',
    'Kevin Durant',
    'Khris Middleton',
    'Klay Thompson',
    'Kyrie Irving',
    'LaMelo Ball',
    'LeBron James',
    'Luka Doncic',
    'Malcolm Brogdon',
    'Miles Bridges',
    'Nikola Jokic',
    'Norman Powell',
    'Pascal Siakam',
    'Paul George',
    'RJ Barrett',
    'Russell Westbrook',
    'Shai Gilgeous-Alexander',
    'Terry Rozier',
    'Trae Young',
    'Tyler Herro',
    'Zach LaVine'
  ];

  export default NBAPlayers;
  