const NFLplayers = [
    "Patrick Mahomes",
    "Josh Allen",
    "Joe Burrow",
    "Geno Smith",
    "Jared Goff",
    "Kirk Cousins",
    "Aaron Rodgers",
    "Trevor Lawrence",
    "Tua Tagovailoa",
    "Justin Herbert",
    "Tom Brady",
    "Derek Carr",
    "Dak Prescott",
    "Jalen Hurts",
    "Andy Dalton",
    "Justin Fields",
    "Davis Mills",
    "Lamar Jackson",
    "Jimmy Garoppolo",
    "Russell Wilson",
    "Daniel Jones",
    "Marcus Mariota",
    "Mac Jones",
    "Kyler Murray",
    "Matt Ryan",
    "Brock Purdy",
    "Ryan Tannehill",
    "Taylor Heinicke",
    "Jacoby Brissett",
    "Carson Wentz"
];

export default NFLplayers;